version: '3.8'

services:
  app:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./backend/static:/app/static
      - ./backend/templates:/app/templates